export const intervalStepsObject = {
  Unison: {
    do: ["do", "do"],
    re: ["re", "re"],
    mi: ["mi", "mi"],
    do_b: ["do_b", "doo_b"],
    re_b: ["re_b", "ree_b"],
    mi_b: ["mi_b", "mii_b"],
    mi_q: ["mi_q", "mii_q"],
  },
  "Minor Second": {
    do: ["do", "re_b"],
    re: ["re", "mi_b"],
    mi: ["mi", "fa"],
    do_b: ["do_b", "do"],
    re_b: ["re_b", "re"],
    mi_b: ["mi_b", "mi"],
    mi_q: ["mi_q", "fa_q"],
  },
  "Major Second": {
    do: ["do", "re"],
    re: ["re", "mi"],
    mi: ["mi", "fa_d"],
    do_b: ["do_b", "re_b"],
    re_b: ["re_b", "mi_b"],
    mi_b: ["mi_b", "fa"],
    mi_q: ["mi_q", "fa_d_q"],
  },
  "Three Quarters": {
    do: ["do", "re_q"],
    re: ["re", "mi_q"],
    mi: ["mi", "fa_d_q"],
    do_b: ["do_b", "do_d_q"],
    re_b: ["re_b", "mi_b_q"],
    mi_b: ["mi_b", "fa_q"],
    mi_q: ["mi_q", "fa"],
  },
  "Minor Third": {
    do: ["do", "mi_b"],
    re: ["re", "fa"],
    mi: ["mi", "sol"],
    do_b: ["do_b", "mi"],
    re_b: ["re_b", "mi"],
    mi_b: ["mi_b", "sol_b"],
    mi_q: ["mi_q", "mii_q"],
  },
  Octave: {
    do: ["do", "doo"],
    re: ["re", "ree"],
    mi: ["mi", "mii"],
    do_b: ["do_b", "doo_b"],
    re_b: ["re_b", "ree_b"],
    mi_b: ["mi_b", "mii_b"],
    mi_q: ["mi_q", "mii_q"],
  },
};
